// Router preset sync: keep llama-server `--models-preset` INI files in step
// with the models folder, so a model downloaded or deleted in Dive does not
// have to be hand-written into the preset afterwards.
//
// This is OFF by default and only ever touches files whose paths the user
// typed in. Dive's own managed mode spawns `llama-server -m <file>` directly
// and has no use for presets — this exists purely for setups that run
// llama-server in router mode from a LaunchAgent.
//
// Everything Dive writes lives between two marker comments. Text outside the
// block — hand-written sections, `[*]` globals, comments — is copied through
// untouched and is never parsed as something to own. Two further rules keep
// Dive out of the user's way:
//
//   - a section name that already exists outside the block is never re-created
//     (so an alias like [text-embedding-nomic-embed-text-v2-moe] keeps its
//     name, and with it the library vector index that is keyed to that name);
//   - a .gguf already referenced by a `model =` line outside the block is
//     never given a second section, which would make the router advertise one
//     file as two models.
//
// Two things work differently, and by LOCATION rather than authorship. A
// section pointing at a file inside the models folder describes a model Dive
// manages, so:
//
//   - REMOVAL: when that file is deleted the section goes with it, wherever in
//     the preset it lives. Leaving it behind is worse than editing a
//     hand-written line — the router keeps advertising a model that cannot
//     load. Any deletion takes a dated .bak first.
//   - ctx-size: the CONTEXT slider sets it, so Dive brings that one line into
//     line even in a hand-written section. Otherwise the slider does nothing
//     for such a model while the token counter reports the real (different)
//     figure, and the user has three numbers and no way to tell which is true.
//     Only that key is rewritten; every other byte of the section is kept.
//
// Sections pointing outside the models folder are never removed or edited, only
// reported.
"use strict";

const fs = require("fs");
const path = require("path");

const BLOCK_START =
  "; >>> dive-managed — regenerated by Dive, edits inside this block are lost >>>";
const BLOCK_END = "; <<< dive-managed <<<";
const BLOCK_START_RE = /^\s*;\s*>>>\s*dive-managed\b.*$/;
const BLOCK_END_RE = /^\s*;\s*<<<\s*dive-managed\s*<<<\s*$/;

// Keys that describe one specific model and must never be inherited from a
// sibling section or from `[*]`.
const PER_MODEL_KEYS = new Set(["model", "mmproj", "alias"]);
// Chat-only: a template engine setting is meaningless on an embedding server.
const CHAT_ONLY_KEYS = new Set([
  "jinja",
  "chat-template",
  "chat-template-file",
]);

function splitLines(text) {
  return String(text || "").split(/\r?\n/);
}

// Split a preset into the text before Dive's block, the block itself, and the
// text after it. A file with no block yet reports found:false and everything
// as `before`, so the block can be appended.
function splitManagedBlock(text) {
  const lines = splitLines(text);
  const start = lines.findIndex((l) => BLOCK_START_RE.test(l));
  if (start === -1) {
    return { before: lines, managed: [], after: [], found: false };
  }
  const rest = lines.slice(start + 1).findIndex((l) => BLOCK_END_RE.test(l));
  // An unterminated block means someone truncated the file mid-write. Treat
  // everything from the marker on as Dive's, rather than guessing.
  const end = rest === -1 ? lines.length - 1 : start + 1 + rest;
  return {
    before: lines.slice(0, start),
    managed: lines.slice(start + 1, end),
    after: lines.slice(end + 1),
    found: true,
  };
}

// Minimal INI reader: `[section]` headers and `key = value` pairs, `;` and `#`
// comments. Values keep their inline spacing; llama-server's own parser is
// equally forgiving.
function parseSections(lines) {
  const sections = [];
  let current = null;
  for (const raw of lines) {
    const line = String(raw || "").trim();
    if (!line || line.startsWith(";") || line.startsWith("#")) continue;
    const header = line.match(/^\[(.+)\]$/);
    if (header) {
      current = { name: header[1].trim(), entries: new Map() };
      sections.push(current);
      continue;
    }
    const eq = line.indexOf("=");
    if (eq === -1 || !current) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim();
    if (key) current.entries.set(key, value);
  }
  return sections;
}

// Section names and model paths that are off limits because a human wrote
// them. Paths are resolved so "./x.gguf" and an absolute path collide.
function guardFrom(sections, modelsDir) {
  const names = new Set();
  const modelPaths = new Set();
  for (const section of sections) {
    names.add(section.name);
    const model = section.entries.get("model");
    if (model) modelPaths.add(path.resolve(modelsDir, model));
  }
  return { names, modelPaths };
}

// Settings a generated section should carry so it behaves like the rest of the
// file. `[*]` globals win; where there are none, keys that every existing
// section agrees on are treated as house style (that is how the embed preset,
// which has no `[*]`, still yields sleep-idle-seconds).
//
// This matters because a named section may REPLACE the globals rather than
// merge with them, so a generated section that omits them would silently run
// with different settings from its neighbours.
function inheritedDefaults(sections) {
  const star = sections.find((s) => s.name === "*");
  const named = sections.filter((s) => s.name !== "*");
  const out = new Map();
  if (named.length) {
    const [first, ...others] = named;
    for (const [key, value] of first.entries) {
      if (PER_MODEL_KEYS.has(key)) continue;
      if (others.every((s) => s.entries.get(key) === value))
        out.set(key, value);
    }
  }
  if (star) {
    for (const [key, value] of star.entries) {
      if (PER_MODEL_KEYS.has(key)) continue;
      out.set(key, value);
    }
  }
  return out;
}

function renderSection(name, entries) {
  const lines = [`[${name}]`];
  for (const [key, value] of entries) lines.push(`${key} = ${value}`);
  return lines.join("\n");
}

// Vision adapters are identified by their GGUF architecture ("clip"), but a
// header that fails to parse — a truncated or half-downloaded file — would
// leave one looking like an ordinary model and get it registered as something
// chattable. The name check is the same one routes/chat.js already applies to
// the model list, and costs nothing.
function looksLikeProjector(model) {
  return (
    model.isProjector === true ||
    model.arch === "clip" ||
    /mmproj/i.test(String(model.file || ""))
  );
}

function sectionNameFor(file) {
  return String(file).replace(/\.gguf$/i, "");
}

// The context Dive should ask for: what the user chose on the CONTEXT slider,
// capped by what the GGUF was actually trained for. A model's trained maximum
// is not a safe default — Ministral 3 3B is a 3B model with a 256K window and
// no sliding-window discount, so its full context wants more KV cache than a
// 24 GB machine has — which is exactly why the chosen value has to be honoured.
function desiredCtx(model) {
  return model.maxCtx > 0
    ? Math.min(model.ctx || model.maxCtx, model.maxCtx)
    : model.ctx;
}

function fileExists(p) {
  try {
    return fs.statSync(p).isFile();
  } catch {
    return false;
  }
}

// Chat preset: EVERY chat model gets a section.
//
// `--models-dir` is not a substitute. A router scans that folder once, when it
// starts, so a model downloaded afterwards is invisible to it — loading it
// fails with "not registered in the external llama-server". Writing a section
// makes the model explicit and, just as importantly, means the preset file
// changes on every download and delete, which is what triggers the restart
// that puts the change into effect.
//
// A model that appears in both the preset and the scanned folder is listed
// once, from the preset, so this never doubles up with --models-dir.
function buildChatSections(models, options) {
  const { modelsDir, guard, defaults, exclude } = options;
  const out = [];
  const skipped = [];
  for (const model of models) {
    if (looksLikeProjector(model) || model.embedding) continue;
    if (exclude.has(model.file)) continue;
    const name = sectionNameFor(model.file);
    const modelPath = path.join(modelsDir, model.file);
    if (guard.names.has(name)) {
      skipped.push({ file: model.file, reason: "section already in the file" });
      continue;
    }
    if (guard.modelPaths.has(path.resolve(modelPath))) {
      skipped.push({ file: model.file, reason: "file already has a section" });
      continue;
    }
    if (!fileExists(modelPath)) {
      skipped.push({ file: model.file, reason: "model file missing" });
      continue;
    }
    const entries = new Map();
    entries.set("model", modelPath);
    // Vision models need their projector paired explicitly; auto-discovery
    // cannot do that. A projector path that does not resolve is worse than no
    // projector at all, so it is only written when the file is really there.
    if (model.projector) {
      const projectorPath = path.join(modelsDir, model.projector);
      if (fileExists(projectorPath)) {
        entries.set("mmproj", projectorPath);
      } else {
        skipped.push({ file: model.file, reason: "projector missing" });
      }
    }
    // The context the user chose for THIS model, capped by what the GGUF was
    // trained for. Set before the inherited defaults so it wins over a global
    // `ctx-size` — a per-model choice is more specific than `[*]`.
    //
    // Without this the section inherited `[*] ctx-size = 0`, which means "use
    // the trained maximum", and the CONTEXT slider did nothing for any
    // router-served model. That is not just a cosmetic loss: a small model with
    // a very long trained window (Ministral 3 3B is 3B parameters with a 256K
    // context and no sliding-window discount) asks for a KV cache far larger
    // than the machine has, and loading it takes the whole machine down.
    const ctx = desiredCtx(model);
    if (ctx > 0) entries.set("ctx-size", String(ctx));
    for (const [key, value] of defaults) {
      if (!entries.has(key)) entries.set(key, value);
    }
    // Jinja chat templates, which native tool calling needs — llama-server
    // answers "tools param requires --jinja flag" without them. Dive's own
    // managed servers always pass --jinja, so a router-served model should not
    // be the odd one out.
    //
    // It cannot come from `defaults` alone: those only carry what the file
    // already says, so a preset with no `[*]` (or with sections that disagree)
    // yielded sections holding nothing but `model =`, and tool calling failed
    // on every model Dive added. Only set when the file has not spoken.
    if (!entries.has("jinja")) entries.set("jinja", "true");
    out.push({ name, entries });
  }
  return { sections: out, skipped };
}

// Embedding preset: the embed router runs without `--models-dir`, so nothing
// is auto-discovered and every embedding model needs its own section.
function buildEmbedSections(models, options) {
  const { modelsDir, guard, defaults, exclude } = options;
  const out = [];
  const skipped = [];
  for (const model of models) {
    if (looksLikeProjector(model) || !model.embedding) continue;
    if (exclude.has(model.file)) continue;
    const name = sectionNameFor(model.file);
    const modelPath = path.join(modelsDir, model.file);
    if (guard.names.has(name)) {
      skipped.push({ file: model.file, reason: "section already in the file" });
      continue;
    }
    if (guard.modelPaths.has(path.resolve(modelPath))) {
      skipped.push({ file: model.file, reason: "file already has a section" });
      continue;
    }
    if (!fileExists(modelPath)) {
      skipped.push({ file: model.file, reason: "model file missing" });
      continue;
    }
    const entries = new Map();
    entries.set("model", modelPath);
    // An embedding model wants its trained context, not a chat-sized one, so
    // the GGUF's own maximum caps whatever Dive has stored for it.
    const ctx = desiredCtx(model);
    if (ctx > 0) entries.set("ctx-size", String(ctx));
    if (model.gpuLayers > 0)
      entries.set("n-gpu-layers", String(model.gpuLayers));
    entries.set("embeddings", "true");
    for (const [key, value] of defaults) {
      if (CHAT_ONLY_KEYS.has(key) || entries.has(key)) continue;
      entries.set(key, value);
    }
    out.push({ name, entries });
  }
  return { sections: out, skipped };
}

// Is this path inside the models folder Dive manages?
function insideModelsDir(resolved, modelsDir) {
  const dir = path.resolve(modelsDir);
  return resolved === dir || resolved.startsWith(dir + path.sep);
}

// Sections describing a model file that is gone (or is being deleted right
// now). Ownership is by LOCATION, not by who typed it: a section pointing at
// the models folder describes a file Dive manages, so when that file goes the
// section goes with it — otherwise the router keeps advertising a model that
// cannot load. A section pointing anywhere else is somebody else's and is only
// ever reported.
function findDeadSections(sections, modelsDir, exclude) {
  const removable = [];
  const foreign = [];
  for (const section of sections) {
    if (section.name === "*") continue;
    const model = section.entries.get("model");
    if (!model) continue;
    const resolved = path.resolve(modelsDir, model);
    const dead = exclude.has(path.basename(resolved)) || !fileExists(resolved);
    if (!dead) continue;
    const entry = { section: section.name, model: resolved };
    if (insideModelsDir(resolved, modelsDir)) removable.push(entry);
    else foreign.push(entry);
  }
  return { removable, foreign };
}

// Drop whole `[section]` blocks from raw text by name, keeping every other
// line — including comments — byte for byte. Comment lines immediately above a
// removed section go with it: they describe the model that just left.
function removeSections(lines, names) {
  if (!names.size) return lines;
  const out = [];
  let dropping = false;
  let pendingComments = [];
  for (const raw of lines) {
    const line = String(raw ?? "");
    const trimmed = line.trim();
    const header = trimmed.match(/^\[(.+)\]$/);
    if (header) {
      dropping = names.has(header[1].trim());
      if (dropping) {
        pendingComments = [];
        continue;
      }
      out.push(...pendingComments, line);
      pendingComments = [];
      continue;
    }
    if (dropping) {
      // A blank line ends the section being dropped.
      if (!trimmed) dropping = false;
      continue;
    }
    if (trimmed.startsWith(";") || trimmed.startsWith("#")) {
      pendingComments.push(line);
      continue;
    }
    // A blank line breaks the association: comments above it belong to what
    // came before, not to the next section, so they are kept even when that
    // section is removed. Only an unbroken run of comments directly above a
    // header is treated as describing it.
    out.push(...pendingComments, line);
    pendingComments = [];
  }
  out.push(...pendingComments);
  return out;
}

// Force `key = value` inside named sections that already exist, rewriting just
// that one line and leaving every other byte — comments, ordering, spacing —
// exactly as it was. Keys not already present are appended at the end of the
// section.
//
// This is how the CONTEXT slider reaches a model whose section somebody wrote
// by hand. Ownership is the same rule the delete path uses, by LOCATION: a
// section pointing into the models folder describes a model Dive manages, so
// the setting Dive's UI controls for it has to win. Otherwise the slider, the
// token counter and the running model disagree and none of them can be trusted.
// Sections pointing outside the models folder are never passed in here.
function setSectionKeys(lines, updates) {
  if (!updates.size) return lines;
  const out = [];
  let current = null;
  let applied = null;
  // Emit whatever this section still owes before leaving it.
  const flush = () => {
    if (!current || !applied) return;
    for (const [key, value] of updates.get(current) || []) {
      if (!applied.has(key)) out.push(`${key} = ${value}`);
    }
  };
  for (const raw of lines) {
    const line = String(raw ?? "");
    const trimmed = line.trim();
    const header = trimmed.match(/^\[(.+)\]$/);
    if (header) {
      flush();
      current = header[1].trim();
      applied = new Set();
      out.push(line);
      continue;
    }
    // A blank line ends the section, so anything owed goes in above it.
    if (!trimmed && current) {
      flush();
      current = null;
      applied = null;
      out.push(line);
      continue;
    }
    const wanted = current ? updates.get(current) : null;
    if (wanted) {
      const eq = line.indexOf("=");
      if (eq !== -1) {
        const key = line.slice(0, eq).trim();
        if (wanted.has(key)) {
          out.push(`${key} = ${wanted.get(key)}`);
          applied.add(key);
          continue;
        }
      }
    }
    out.push(line);
  }
  flush();
  return out;
}

function renderBlock(sections) {
  if (!sections.length) return [BLOCK_START, BLOCK_END].join("\n");
  const body = sections
    .map((s) => renderSection(s.name, s.entries))
    .join("\n\n");
  return [BLOCK_START, "", body, "", BLOCK_END].join("\n");
}

// Put the rendered block back into the file, preserving everything around it.
function applyBlock(text, block, hadFile) {
  const { before, after, found } = splitManagedBlock(text);
  if (found) {
    return [...before, ...splitLines(block), ...after].join("\n");
  }
  const head = hadFile ? [...before] : [];
  // Keep exactly one blank line between existing content and the block.
  while (head.length && head[head.length - 1].trim() === "") head.pop();
  const parts = head.length ? [...head, "", block] : [block];
  return parts.join("\n") + "\n";
}

// Build the new text for one preset file. Pure apart from reading the file and
// stat-ing model paths — nothing is written here, so callers can dry-run.
function planPreset(options) {
  const { filePath, kind, models, modelsDir, exclude = new Set() } = options;
  const hadFile = fileExists(filePath);
  const before = hadFile ? fs.readFileSync(filePath, "utf8") : "";
  const split = splitManagedBlock(before);
  const outsideRaw = parseSections([...split.before, ...split.after]);
  // Sections whose model file has gone come out first, so the rest of the plan
  // is built against what the preset will actually contain.
  const dead = findDeadSections(outsideRaw, modelsDir, exclude);
  const removeNames = new Set(dead.removable.map((d) => d.section));
  const keptBefore = removeSections(split.before, removeNames);
  const keptAfter = removeSections(split.after, removeNames);
  const outside = parseSections([...keptBefore, ...keptAfter]);
  const guard = guardFrom(outside, modelsDir);
  const defaults = inheritedDefaults(outside);
  const build = kind === "embed" ? buildEmbedSections : buildChatSections;
  const { sections, skipped } = build(models, {
    modelsDir,
    guard,
    defaults,
    exclude,
  });
  // A model already described by a hand-written section gets no section of its
  // own — but its ctx-size is still Dive's to set, by the same location rule
  // that lets a delete remove such a section. Without this the CONTEXT slider
  // silently does nothing for those models, and the slider, the token counter
  // and the running model all report different numbers.
  const ctxByModelPath = new Map();
  for (const model of models) {
    if (looksLikeProjector(model)) continue;
    if (exclude.has(model.file)) continue;
    if (kind === "embed" ? !model.embedding : model.embedding) continue;
    const ctx = desiredCtx(model);
    if (ctx > 0) {
      ctxByModelPath.set(path.resolve(modelsDir, model.file), String(ctx));
    }
  }
  const retuned = [];
  const updates = new Map();
  for (const section of outside) {
    if (section.name === "*") continue;
    const raw = section.entries.get("model");
    if (!raw) continue;
    const resolved = path.resolve(modelsDir, raw);
    // Somebody else's model, somewhere else on disk: never touched.
    if (!insideModelsDir(resolved, modelsDir)) continue;
    const ctx = ctxByModelPath.get(resolved);
    if (ctx === undefined) continue;
    if (section.entries.get("ctx-size") === ctx) continue;
    updates.set(section.name, new Map([["ctx-size", ctx]]));
    retuned.push({
      section: section.name,
      from: section.entries.get("ctx-size") ?? "",
      to: ctx,
    });
  }
  const tunedBefore = setSectionKeys(keptBefore, updates);
  const tunedAfter = setSectionKeys(keptAfter, updates);
  // Nothing to manage and no block yet: leave the file exactly as it is rather
  // than stamping an empty block (and a .dive-backup) onto a preset where
  // every model is already hand-written. Once a block exists it is always
  // rewritten, so emptying it is how the last managed section is removed.
  const hasBlock = split.found;
  const rewroteOutside = removeNames.size > 0 || updates.size > 0;
  const trimmed = rewroteOutside
    ? [
        ...tunedBefore,
        ...(hasBlock ? [BLOCK_START, ...split.managed, BLOCK_END] : []),
        ...tunedAfter,
      ].join("\n")
    : before;
  const after =
    !sections.length && !hasBlock
      ? trimmed
      : applyBlock(trimmed, renderBlock(sections), hadFile);
  return {
    filePath,
    kind,
    existed: hadFile,
    changed: after !== before,
    before,
    after,
    managed: sections.map((s) => s.name),
    skipped,
    // Sections this plan deletes because their model file is gone.
    removed: dead.removable,
    // Dead sections pointing outside the models folder — reported only.
    stale: dead.foreign,
    // Hand-written sections whose ctx-size was brought into line with the
    // CONTEXT slider, so a caller can say what it changed and why.
    retuned,
  };
}

// Write the planned text. The original is copied to <file>.dive-backup once,
// the first time Dive ever touches it, and the new text lands via a temp file
// + rename so a crash mid-write cannot leave a truncated preset behind — a
// half-written preset would take the router's models down with it.
function commitPlan(plan) {
  if (!plan.changed) return { written: false, backup: "" };
  const dir = path.dirname(plan.filePath);
  fs.mkdirSync(dir, { recursive: true });
  let backup = "";
  if (plan.existed) {
    const candidate = `${plan.filePath}.dive-backup`;
    if (!fs.existsSync(candidate)) {
      fs.copyFileSync(plan.filePath, candidate);
      backup = candidate;
    }
    // Deleting a section is the one irreversible edit, so it always gets its
    // own dated copy rather than relying on the once-only backup above.
    if ((plan.removed || []).length) {
      const stamp = new Date().toISOString().replace(/[:.]/g, "-");
      const dated = `${plan.filePath}.${stamp}.bak`;
      fs.copyFileSync(plan.filePath, dated);
      backup = backup || dated;
    }
  }
  const tmp = `${plan.filePath}.dive-tmp-${process.pid}`;
  try {
    fs.writeFileSync(tmp, plan.after, "utf8");
    fs.renameSync(tmp, plan.filePath);
  } catch (e) {
    fs.rmSync(tmp, { force: true });
    throw e;
  }
  return { written: true, backup };
}

module.exports = {
  BLOCK_START,
  BLOCK_END,
  splitManagedBlock,
  parseSections,
  guardFrom,
  inheritedDefaults,
  buildChatSections,
  buildEmbedSections,
  findDeadSections,
  removeSections,
  setSectionKeys,
  desiredCtx,
  renderBlock,
  applyBlock,
  planPreset,
  commitPlan,
  sectionNameFor,
};
